app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('equipments','EquipmentsController');
Route::resource('checkequipments','CheckEquipmentsController');
Route::resource('rooms','RoomsController');
Route::resource('departments','DepartmentsController');
Route::resource('companys','CompanysController');
Route::resource('lostequipments','LostEquipmentsController');
Route::resource('repairequipments','RepairEquipmentsController');
Route::resource('changerooms','ChangeRoomsController');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/app/Http/Controllers/CompanysController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\CompanysModel;
use Carbon\Carbon;

class CompanysController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companys = DB::table('Companys')->get();
        return view('companys.index', ['companys'=>$companys]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companys.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::beginTransaction();
        try {

            DB::table("Companys")->insert([
                'comp_id'=>$request->comp_id,
                'comp_name'=>$request->comp_name,
                'comp_addr'=>$request->comp_addr,
                'create_by'=>$request->user()->name,
                'update_by'=>$request->user()->name,
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ]);

        } catch(ValidationException $e) {
            DB::rollback();
        }

        DB::commit();

    return redirect('companys');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $companys = CompanysModel::find($id);
        return view('companys.create', ['companys'=>$companys]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $companys = CompanysModel::find($id);

        return view('companys.edit', compact('companys'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'comp_addr'=> 'required',
            'comp_id'=> 'required',
            'comp_name'=> 'required',
        ]);

        $company = CompanysModel::find($id);

        $company->comp_id = $request->get('comp_id');
        $company->comp_name = $request->get('comp_name');
        $company->comp_addr = $request->get('comp_addr');
        $company->update_by = $request->user()->name;
        $company->save();
        return redirect('companys');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = CompanysModel::find($id);

        $company->delete();
        return redirect('companys');
    }
}

app/resources/views/companys/create.blade.php
@extends('layouts.app')

@section('content')

@guest
 <h1>You need to login</h1>
  <li class="nav-item">
    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
  </li>
  @if (Route::has('register'))
    <li class="nav-item">
      <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
    </li>
  @endif
@else
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <form action="{{ route('companys.store') }}" method="post">
                @csrf
                    <table class="table" border=1>
                        <tbody>
                            <tr>
                                <td>comp_id </td>
                                <td><input type="text" name="comp_id" require> </td>
                            </tr>
                            <tr>
                                <td>comp_name </td>
                                <td><input type="text" name="comp_name" require> </td>
                            </tr>
                            <tr>
                                <td>comp_addr </td>
                                <td><input type="text" name="comp_addr" require> </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="submit" value="เพิ่มข้อมูล">
                                    <a class="btn btn-default btn-close" href="{{ URL::previous() }}">Cancel</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
@endguest
@endsection

app/resources/views/companys/edit.blade.php
@extends('layouts.app')

@section('content')

@guest
 <h1>You need to login</h1>
  <li class="nav-item">
    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
  </li>
  @if (Route::has('register'))
    <li class="nav-item">
      <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
    </li>
  @endif
@else
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <form action="{{ route('companys.update',$companys->id) }}" method="post">
                @method('PUT')
                @csrf
                    <table class="table" border=1>
                        <tbody>
                            <tr>
                                <td>รหัสบริษัท </td>
                                <td><input type="text" name="comp_id" value="{{ $companys->comp_id }}" require> </td>
                            </tr>
                            <tr>
                            <tr>
                                <td>ชื่อบริษัท </td>
                                <td><input type="text" name="comp_name" value="{{ $companys->comp_name }}" require> </td>
                            </tr>
                            <tr>
                                <td>ที่อยู่ </td>
                                <td><input type="text" name="comp_addr" value="{{ $companys->comp_addr }}" require> </td>
                            </tr>

                            
                            <tr>
                                <td>
                                    <input type="submit" value="edit">
                                    <a class="btn btn-default btn-close" href="{{ URL::previous() }}">Cancel</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
@endguest
@endsection

app/resources/views/companys/index.blade.php
@extends('layouts.app')

@section('content')

@guest
 <h1>You need to login</h1>
  <li class="nav-item">
    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
  </li>
  @if (Route::has('register'))
    <li class="nav-item">
      <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
    </li>
  @endif
@else
<a href="{{ route('home') }}">Home</a><br>
  <table class="table table-striped table-bordered">
    <thead>
        <tr class="bg-primary text-white">
            <th>comp_id</th>
            <th>comp_name</th>
            <th>comp_addr</th>
            <th>create_by</th>
            <th>update_by</th>
            <th>created_at</th>
            <th>updated_at</th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($companys as $company)
        <tr>
            <td>{{ $company->comp_id }}</td>
            <td>{{ $company->comp_name }}</td>
            <td>{{ $company->comp_addr }}</td>
            <td>{{ $company->create_by }}</td>
            <td>{{ $company->update_by }}</td>
            <td>{{ $company->created_at }}</td>
            <td>{{ $company->updated_at }}</td>
            <td>
              <a href="{{ route('companys.edit',$company->id) }}" class="btn btn-primary">Edit </a>
              <form action="{{ route('companys.destroy',$company->id) }}" method="post">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Delete</button>
              </form>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
<a class="btn btn-default btn-close" href="{{ URL::previous() }}">Back</a>
@endguest
@endsection