app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('equipments','EquipmentsController');
Route::resource('checkequipments','CheckEquipmentsController');
Route::resource('rooms','RoomsController');
Route::resource('departments','DepartmentsController');
Route::resource('companys','CompanysController');
Route::resource('lostequipments','LostEquipmentsController');
Route::resource('repairequipments','RepairEquipmentsController');
Route::resource('changerooms','ChangeRoomsController');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/app/Http/Controllers/EquipmentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\EquipmentsModel;
use App\DepartmentsModel;
use App\CompanysModel;
use App\RoomsModel;
use Carbon\Carbon;


class EquipmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $equipments = DB::table('Equipments')->get();
        
        $equipments = DB::table('Equipments')
        ->join('Companys', 'Equipments.comp_id', '=', 'Companys.comp_id')
        ->join('Rooms', 'Equipments.room_id', '=', 'Rooms.room_id')
        ->join('Departments', 'Equipments.dep_id', '=', 'Departments.dep_id')
        ->select('Equipments.*', 'Companys.comp_name', 'Rooms.room_name', 'Departments.dep_name')
        ->get();
        return view('equipments.index', ['equipments'=>$equipments]);///
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = DepartmentsModel::all();
        $companys = CompanysModel::all();
        $rooms = RoomsModel::all();
        return view('equipments.create', compact('departments','companys','rooms'));//
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'eq_name'=> 'required',
            'eq_serialnumber'=> 'required',
            'comp_id'=> 'required',
            'dep_id'=> 'required',
        ]);

        $equipments = new EquipmentsModel;
        $equipments->eq_serialnumber = $request->eq_serialnumber;
        $equipments->eq_name = $request->eq_name;
        $equipments->eq_brand = $request->eq_brand;
        $equipments->eq_status = 'available';
        $equipments->import_date = Carbon::now()->toDateString();
        $equipments->export_date = $request->export_date;
        $equipments->comp_id = $request->comp_id;
        $equipments->dep_id = $request->dep_id;
        $equipments->room_id = $request->room_id;
        $equipments->create_by = $request->user()->name;
        $equipments->update_by = $request->user()->name;
        $equipments->save();

        return redirect('equipments');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $equipments = EquipmentsModel::find($id);
        return view('checkequipments.create', ['equipments'=>$equipments]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $equipment = EquipmentsModel::find($id);
        $departments = DepartmentsModel::all();
        $companys = CompanysModel::all();

        return view('equipments.edit', compact('equipment','departments','companys'));//
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'eq_name'=> 'required',
            'comp_id'=> 'required',
            'dep_id'=> 'required',
        ]);

        $equipment = EquipmentsModel::find($id);

        $equipment->eq_name = $request->get('eq_name');
        $equipment->eq_brand = $request->get('eq_brand');
        $equipment->export_date = $request->get('export_date');
        $equipment->comp_id = $request->get('comp_id');
        $equipment->dep_id = $request->get('dep_id');
        $equipment->update_by = $request->user()->name;
        $equipment->save();
        return redirect('equipments');//
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $equipment = EquipmentsModel::find($id);

        $equipment->delete();
        return redirect('equipments');
    }
}

app/resources/views/equipments/create.blade.php
@extends('layouts.app')

@section('content')

@guest
 <h1>You need to login</h1>
  <li class="nav-item">
    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
  </li>
  @if (Route::has('register'))
    <li class="nav-item">
      <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
    </li>
  @endif
@else
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <form action="{{ route('equipments.store') }}" method="post">
                @csrf
                    <table class="table" border=1>
                        <tbody>
                            <tr>
                                <td>serialnumber </td>
                                <td><input type="text" name="eq_serialnumber" require> </td>
                            </tr>
                            <tr>
                                <td>ชื่อวัสดุ </td>
                                <td><input type="text" name="eq_name" require> </td>
                            </tr>
                            <tr>
                                <td>ยี่ห้อ </td>
                                <td><input type="text" name="eq_brand" require> </td>
                            </tr>
                            <tr>
                                <td>วันหมดอายุ </td>
                                <td><input type="date" name="export_date" require> </td>
                            </tr>
                            <tr>
                                <td>บริษัท </td>
                                <td><select name="comp_id">
                                @foreach ($companys as $company)
                                    <option value="{{ $company->comp_id }}">{{$company->comp_name}}</option>
                                @endforeach
                                </select>
                                </td>
                            </tr>
                            <tr>
                                <td>หน่วยงาน </td>
                                <td><select name="dep_id">
                                @foreach ($departments as $department)
                                    <option value="{{ $department->dep_id }}">{{$department->dep_name}}</option>
                                @endforeach
                                </select></td>
                            </tr>
                            <tr>
                                <td>ห้อง </td>
                                <td><select name="room_id">
                                @foreach ($rooms as $room)
                                    <option value="{{ $room->room_id }}">{{$room->room_name}}</option>
                                @endforeach
                                </select></td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="submit" value="เพิ่มข้อมูล">
                                    <a class="btn btn-default btn-close" href="{{ URL::previous() }}">Cancel</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
@endguest
@endsection

app/resources/views/equipments/edit.blade.php
@extends('layouts.app')

@section('content')

@guest
 <h1>You need to login</h1>
  <li class="nav-item">
    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
  </li>
  @if (Route::has('register'))
    <li class="nav-item">
      <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
    </li>
  @endif
@else
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <form action="{{ route('equipments.update',$equipment->id) }}" method="post">
                @method('PUT')
                @csrf
                    <table class="table" border=1>
                        <tbody>
                            <tr>
                                <td>รหัส </td>
                                <td><input type="text" name="eq_serialnumber" value="{{ $equipment->eq_serialnumber }}" readonly> </td>
                            </tr>
                            <tr>
                            <tr>
                                <td>ชื่อวัสดุ </td>
                                <td><input type="text" name="eq_name" value="{{ $equipment->eq_name }}" require> </td>
                            </tr>
                            <tr>
                                <td>ยี่ห้อ </td>
                                <td><input type="text" name="eq_brand" value="{{ $equipment->eq_brand }}" require> </td>
                            </tr>

                            <tr>
                                <td>export_date </td>
                                <td><input type="date" name="export_date" value="{{ $equipment->export_date }}" require> </td>
                            </tr>
                            <tr>
                                <td>company </td>
                                <td>
                                <select name="comp_id">
                                @foreach ($companys as $company)
                                    <option value="{{ $company->comp_id }}">{{$company->comp_name}}</option>
                                @endforeach
                                </select>
                                </td>
                            </tr>
                            <tr>
                                <td>department </td>
                                <td>
                                <select name="dep_id">
                                @foreach ($departments as $department)
                                    <option value="{{ $department->dep_id }}">{{$department->dep_name}}</option>
                                @endforeach
                                </select>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="submit" value="edit">
                                    <a class="btn btn-default btn-close" href="{{ URL::previous() }}">Cancel</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
@endguest
@endsection

app/resources/views/equipments/index.blade.php
@extends('layouts.app')

@section('content')

@guest
 <h1>You need to login</h1>
  <li class="nav-item">
    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
  </li>
  @if (Route::has('register'))
    <li class="nav-item">
      <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
    </li>
  @endif
@else
  <a href="{{ route('home') }}">Home</a><br>
  <a href="{{ route('equipments.create') }}">New equipment</a>       <a href="{{ route('rooms.create') }}">New Room</a><br>
  <a href="{{ route('departments.create') }}">New department</a>      <a href="{{ route('companys.create') }}">New company</a><br>
  <table class="table table-striped table-bordered">
    <thead>
        <tr class="bg-primary text-white">
            <th>Name</th>
            <th>Status</th>
            <th>Serialnumber</th>
            <th>Room</th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($equipments as $equipment)
        <tr>
            <td>{{ $equipment->eq_name }}</td>
            <td>{{ $equipment->eq_status }}</td>
            <td>{{ $equipment->eq_serialnumber }}</td>
            <td>{{ $equipment->room_id }}</td>
            <td>
              <a type="button" class="btn btn-info" data-toggle="modal" data-target="#yourModal{{$equipment->id}}"> View </a> | <a href="{{ route('changerooms.show',$equipment->id) }}" class="btn btn-success" method="get">Change room </a> | 
              <a href="{{ route('equipments.edit',$equipment->id) }}" class="btn btn-primary">Edit </a> | <a href="{{ route('equipments.show',$equipment->id) }}" class="btn btn-success" method="get">Change status </a>
              <form action="{{ route('equipments.destroy',$equipment->id) }}" method="post">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Delete</button>
              </form>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

@foreach ($equipments as $e)    
    <div class="modal fade" id="yourModal{{$e->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">{{$e->eq_name}}</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            <table class="table table-hover">
              <tbody>
                <tr>
                  <td>serialnumber</td>
                  <td>{{$e->eq_serialnumber}}</td>
                </tr>
                <tr>
                  <td>brand</td>
                  <td>{{$e->eq_brand}}</td>
                </tr>
                <tr>
                  <td>status</td>
                  <td>{{$e->eq_status}}</td>
                </tr>
                <tr>
                  <td>import_date</td>
                  <td>{{$e->import_date}}</td>
                </tr>
                <tr>
                  <td>export_date</td>
                  <td>{{$e->export_date}}</td>
                </tr>
                <tr>
                  <td>comp_name</td>
                  <td>{{$e->comp_name}}</td>
                </tr>
                <tr>
                  <td>dep_name</td>
                  <td>{{$e->dep_name}}</td>
                </tr>
                <tr>
                  <td>room_name</td>
                  <td>{{$e->room_name}}</td>
                </tr>
                <tr>
                  <td>create_by</td>
                  <td>{{$e->create_by}}</td>
                </tr>
                <tr>
                  <td>update_by</td>
                  <td>{{$e->update_by}}</td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
<!-- Modal: modalCart -->
@endforeach
@endguest
@endsection